### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'MainThread'.

### ISSUE THREAD

**Issue by BlueBerrySans365** [qwertyquerty/pypresence#189]
Hello, just got this error:
```
Traceback (most recent call last):
  File "/home/nicksalt/gits/project/test.py", line 17, in <module>
    RPC = Presence(client_id)
  File "/home/nicksalt/.local/lib/python3.10/site-packages/pypresence/presence.py", line 13, in __init__
    super().__init__(*args, **kwargs)
  File "/home/nicksalt/.local/lib/python3.10/site-packages/pypresence/baseclient.py", line 33, in __init__
    self.update_event_loop(get_event_loop())
  File "/home/nicksalt/.local/lib/python3.10/site-packages/pypresence/utils.py", line 52, in get_event_loop
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'MainThread'.
```
I don't know how to fix it... OS: Arch Linux x64

**Comment by BlueBerrySans365** [comment]
Fixed with changing ``loop = asyncio.get_event_loop()`` to ``loop = asyncio.new_event_loop()`` in utils.py
