### ISSUE TITLE
There is no current event loop

### ISSUE THREAD

**Issue by LcyDev** [qwertyquerty/pypresence#199]
This happens with the following:
```py
Presence(client_id)
Presence(client_id, handler=errorHandler)
```

Fixed by adding `loop=asyncio.new_event_loop()`

```cs
Exception in thread Thread-2:
Traceback (most recent call last):
  File "Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "Python38-32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "woodRewritten\src\wood\utils\thread_funcs.py", line 71, in rpcLoop
    RPC = Presence(client_id, handler=errorHandler)
  File "Python38-32\lib\site-packages\pypresence\presence.py", line 13, in __init__
    super().__init__(*args, **kwargs)
  File "Python38-32\lib\site-packages\pypresence\baseclient.py", line 33, in __init__
    self.update_event_loop(get_event_loop())
  File "Python38-32\lib\site-packages\pypresence\utils.py", line 59, in get_event_loop
    loop = asyncio.get_event_loop()
  File "Python38-32\lib\asyncio\events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-2'.
```

**Comment by LcyDev** [comment]
Relates to #169
