### ISSUE TITLE
qwertypls

### ISSUE THREAD

**Issue by kot83** [qwertyquerty/pypresence#2]
```py
kot83-desktop% python3.6 test.py 
{"v": 1, "client_id": "64567352374564"}
{"cmd": "SET_ACTIVITY", "args": {"pid": 12611, "activity": {"state": "ree", "timestamps": {}, "assets": {}, "party": {}, "secrets": {}, "instance": true}}, "nonce": "1522862178.79681730270385742188"}
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    print(RPC.set_activity(state="ree")) #Set the presence
  File "/home/kot83/Documents/pypresence.py", line 256, in set_activity
    return self.loop.run_until_complete(self.read_output())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/kot83/Documents/pypresence.py", line 31, in read_output
    data = await self.sock_reader.read(1024)
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 634, in read
    yield from self._wait_for_data('read')
  File "/usr/local/lib/python3.6/asyncio/streams.py", line 464, in _wait_for_data
    yield from self._waiter
  File "/usr/local/lib/python3.6/asyncio/selector_events.py", line 723, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
```

**Comment by qwertyquerty** [comment]
What did you do to produce this error

**Comment by qwertyquerty** [comment]
@kot83 Sooo, uh, you never replaced the client ID with your own client ID. That is not a real ID.
