### ISSUE TITLE
RPC doesn't work at all

### ISSUE THREAD

**Issue by Mortimer-Kerman** [qwertyquerty/pypresence#207]
Pretty self-explanatory.

I tried to execute this code on Windows 11 in Anaconda Spyder Python 3.9:
```py
from pypresence import Presence

import time


client_id="yes my client id is correct don't bother about it"

RPC = Presence(client_id=client_id)
RPC.connect()

RPC.update(state="test",details="text here",large_image="maintex")

time.sleep(15)
```

And I got this error:
```
Traceback (most recent call last):

  File "C:\Users\29ray\anaconda3\lib\site-packages\spyder_kernels\py3compat.py", line 356, in compat_exec
    exec(code, globals, locals)

  File "c:\users\29ray\desktop\projets scolaires\term\testrichpresence.py", line 16, in <module>
    RPC.connect()

  File "C:\Users\29ray\anaconda3\lib\site-packages\pypresence\presence.py", line 45, in connect
    self.loop.run_until_complete(self.handshake())

  File "C:\Users\29ray\anaconda3\lib\asyncio\base_events.py", line 623, in run_until_complete
    self._check_running()

  File "C:\Users\29ray\anaconda3\lib\asyncio\base_events.py", line 585, in _check_running
    raise RuntimeError(

RuntimeError: Cannot run the event loop while another loop is running
```

**Comment by Mortimer-Kerman** [comment]
> Try installing latest with git and trying again

It's alr

**Comment by Mortimer-Kerman** [comment]
So, what can I do about it?

**Comment by brostosjoined** [comment]
> So, what can I do about it?
> 
> Note: I also have latest asyncio version

what version of python are you on

**Comment by Mortimer-Kerman** [comment]
> > So, what can I do about it?
> > Note: I also have latest asyncio version
> 
> what version of python are you on

Python 3.9.13

**Comment by Mortimer-Kerman** [comment]
Note: I upgraded to Python 3.10.5 and it's still not working

**Comment by brostosjoined** [comment]
> > > So, what can I do about it?
> > > Note: I also have latest asyncio version
> > 
> > 
> > what version of python are you on
> 
> Python 3.9.13

Try using python 3.8

**Comment by Mortimer-Kerman** [comment]
> 

using nest_asyncio doesn't work and I can't afford to downgrade my python version
(yeah I even tried to put it in baseclient)
