### ISSUE TITLE
FileNotFoundError in sock.connect() Ubuntu 18.04

### ISSUE THREAD

**Issue by ToppleKek** [qwertyquerty/pypresence#22]
Hello, I've been trying to solve this issue on Ubuntu 18.04 without much luck. Getting the error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/rhythmbox/plugins/discord-rhythmbox-plugin/discord-status.py", line 9, in <module>
    class discord_status (GObject.Object, Peas.Activatable):
  File "/usr/lib/rhythmbox/plugins/discord-rhythmbox-plugin/discord-status.py", line 11, in discord_status
    RPC.connect()
  File "/home/topkek/.local/lib/python3.6/site-packages/pypresence/presence.py", line 123, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/topkek/.local/lib/python3.6/site-packages/pypresence/presence.py", line 58, in handshake
    self.sock_reader, self.sock_writer = yield from asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.6/asyncio/streams.py", line 134, in open_unix_connection
    lambda: protocol, path, **kwds)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 245, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 455, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```
I've tried reinstalling pypresence with no luck. So far only found this issue on Ubuntu. Debian and Manjaro seem to work fine. Not sure if this is an issue with pypresence or asyncio, but thought I'd start here. Any help is appreciated! Thanks!

**Comment by ToppleKek** [comment]
Whoops, was writing this up quick and forgot some code samples:
```py
class discord_status_dev (GObject.Object, Peas.Activatable):
  RPC = Presence('415207119642689544')
RPC.connect()
...
 self.RPC.update(state="Playback Stopped", details="Rhythmbox Status Plugin", large_image="rhythmbox", small_image="stop", small_text="Stopped")
...
```
Full code is available on my repo at ToppleKek/discord-rhythmbox-plugin
Thanks!

**Comment by qwertyquerty** [comment]
@ToppleKek Is discord running? Are you on Canary?

**Comment by ToppleKek** [comment]
Discord wasn't running, maybe that was the issue... I have an issue open on my repo that I'm trying to solve, I'll let you know if they manage to fix it or have the same issues, thanks.
