### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by jorbo** [qwertyquerty/pypresence#24]
im getting this error when running the quotes example im using Ubuntu 18.04, zsh, vscode, and pipenv .
Not sure what file its referring to?

```Traceback (most recent call last):
  File "/home/jordan/Documents/CustomDiscordRichPresence/core.py", line 9, in <module>
    RPC.connect()  # Start the handshake loop
  File "/home/jordan/.local/share/virtualenvs/CustomDiscordRichPresence-UCeHkaM9/lib/python3.6/site-packages/pypresence/presence.py", line 123, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/jordan/.local/share/virtualenvs/CustomDiscordRichPresence-UCeHkaM9/lib/python3.6/site-packages/pypresence/presence.py", line 58, in handshake
    self.sock_reader, self.sock_writer = yield from asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.6/asyncio/streams.py", line 134, in open_unix_connection
    lambda: protocol, path, **kwds)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 245, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 455, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory```

**Comment by LewdNeko** [comment]
Could you please tell me what happens when you print `RPC.ipc_path`? Thanks.

**Comment by LewdNeko** [comment]
No reply from author. Closing.

**Comment by toxicrecker** [comment]
im having the same issue on my android phone, this is what `RPC.ipc_path` prints
`/data/user/0/ru.iiec.pydroid3/cache/discord-ipc-0`

**Comment by caio-vinicius** [comment]
i'm running pypresence in python 3.7.9 in a container and i'm receive this error:
```
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    RPC.connect() # Start the handshake loop
  File "/usr/local/lib/python3.7/site-packages/pypresence/presence.py", line 41, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/pypresence/baseclient.py", line 121, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/local/lib/python3.7/asyncio/streams.py", line 128, in open_unix_connection
    lambda: protocol, path, **kwds)
  File "/usr/local/lib/python3.7/asyncio/unix_events.py", line 232, in create_unix_connection
    await self.sock_connect(sock, path)
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 473, in sock_connect
    return await fut
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 478, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
did i need discord on the same machine?
```
location of RPC.ipc_path : /tmp/discord-ipc-0

**Comment by caio-vinicius** [comment]
case closed: need to be in a machine with discord on it.
