### ISSUE TITLE
Example #4 not working

### ISSUE THREAD

**Issue by Ekansh-kashyap** [qwertyquerty/pypresence#29]
``Traceback (most recent call last):
  File "F:\somethingy\pyql\test.py", line 8, in <module>
    print(RPC.update(state="Lookie Lookie", details="A test of qwertyquerty's Python Discord RPC wrapper, pypresence!"))  # Set the presence
  File "C:\Users\INDIA\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pypresence\presence.py", line 107, in update
    return self.loop.run_until_complete(self.read_output())
  File "C:\Users\INDIA\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "C:\Users\INDIA\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pypresence\presence.py", line 43, in read_output
    raise ServerError(payload["data"]["message"])
pypresence.exceptions.ServerError: Unknown error``

**Comment by LewdNeko** [comment]
This is an error that PyPresence is raising. Your full code is needed to debug properly.

**Comment by qwertyquerty** [comment]
Youll have to show your code. This can mean your ID is invalid, make sure to set it as a RPC app in the developers tab.

**Comment by Ekansh-kashyap** [comment]
@qwertyquerty Oh, thanks!
