### ISSUE TITLE
[WinError 232] The pipe is being closed

### ISSUE THREAD

**Issue by LewdNeko** [qwertyquerty/pypresence#3]
Using the example rich presence code - getting this:
```py
{"v": 1, "client_id": mmm}
{"cmd": "SET_ACTIVITY", "args": {"pid": 11536, "activity": {"state": "wait", "details": "testing", "timestamps": {}, "assets": {}, "party": {}, "secrets": {}, "instance": true}}, "nonce": "1523592330.50662136077880859375"}
Traceback (most recent call last):
  File "chrome ext.py", line 354, in <module>
    c.set_activity(state="wait", details="testing")
  File "chrome ext.py", line 256, in set_activity
    return self.loop.run_until_complete(self.read_output())
  File "C:\Users\lll\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "chrome ext.py", line 31, in read_output
    data = await self.sock_reader.read(1024)
  File "C:\Users\lll\AppData\Local\Programs\Python\Python36-32\lib\asyncio\streams.py", line 615, in read
    raise self._exception
  File "C:\Users\lll\AppData\Local\Programs\Python\Python36-32\lib\asyncio\proactor_events.py", line 291, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
  File "C:\Users\lll\AppData\Local\Programs\Python\Python36-32\lib\asyncio\windows_events.py", line 457, in send
    ov.WriteFile(conn.fileno(), buf)
BrokenPipeError: [WinError 232] The pipe is being closed```

**Comment by qwertyquerty** [comment]
App ID was incorrect.
