### ISSUE TITLE
FileNotFound Error in Sock.connect(Address)

### ISSUE THREAD

**Issue by MemesOnAStick** [qwertyquerty/pypresence#33]
Hey, i've been trying to solve this error without any luck:
`Traceback (most recent call last):
  File "presence-weeb.py", line 11, in <module>
    RPC.connect()
  File "/usr/local/lib/python3.6/dist-packages/pypresence/presence.py", line 123, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/pypresence/presence.py", line 58, in handshake
    self.sock_reader, self.sock_writer = yield from asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.6/asyncio/streams.py", line 134, in open_unix_connection
    lambda: protocol, path, **kwds)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 245, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 455, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe3291dd7b8>`

Code:
```
`import discord
from discord.ext import commands
import asyncio
from pypresence import Presence

client = commands.Bot(command_prefix = '#')

client.remove_command('help')
presence_id = '472522976638533663'
RPC = Presence(presence_id)
RPC.connect()
client.change_presence(game=None)
@client.event
async def on_ready():
    print("ready to post some weeb shit")
    await client.RPC.update(details = "#help for help", state = "Anime = Mistake", large_text="Please end me", large_image="r-weeb_jpg")





client.run("TOKEN")
`
```

**Comment by qwertyquerty** [comment]
^
