### ISSUE TITLE
Cannot connect when running from a root account

### ISSUE THREAD

**Issue by Aurailus** [qwertyquerty/pypresence#38]
This is my console output, I'm just using example #1.
`aurailus@aurailus-xubuntu:~/Documents/Rich Presence$ sudo python3.6 app.py 
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    RPC.connect()
  File "/home/aurailus/.local/lib/python3.6/site-packages/pypresence/presence.py", line 145, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/aurailus/.local/lib/python3.6/site-packages/pypresence/presence.py", line 80, in handshake
    self.sock_reader, self.sock_writer = yield from asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.6/asyncio/streams.py", line 134, in open_unix_connection
    lambda: protocol, path, **kwds)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 245, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 450, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 455, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
`

Apologies if this is a stupid issue, I'm a bit of a noob at Python.

**Comment by LewdNeko** [comment]
Discord has to be running in order to connect to the RPC.
