### ISSUE TITLE
RPC Update Requires all Inputs

### ISSUE THREAD

**Issue by macoates** [qwertyquerty/pypresence#50]
When I use the example code from examples, (
`RPC.update(state="Lookie Lookie", details="A test of qwertyquerty's Python Discord RPC wrapper, pypresence!")`
), I get the error 

> Traceback (most recent call last):
  File "/Users/user1/Documents/gameplaying.py", line 8, in <module>
    print(RPC.update(state="Lookie Lookie", details="A test of qwertyquerty's Python Discord RPC wrapper, pypresence!"))  # Set the presence
  File "/usr/local/lib/python3.6/site-packages/pypresence/presence.py", line 31, in update
    return self.loop.run_until_complete(self.read_output())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/pypresence/baseclient.py", line 82, in read_output
    raise ServerError(payload["data"]["message"])
pypresence.exceptions.ServerError: Child "activity" fails because child "timestamps" fails because child "start" fails because "start" must be a number
>
When I specify `start`, it asks for another requirement.

(I Don't know if this is a bug or not, please tell me)

**Comment by qwertyquerty** [comment]
This is now fixed in 3.2.1

**Comment by LewdNeko** [comment]
Closing because fixed in 3.2.1
