### ISSUE TITLE
Invalid syntax error.

### ISSUE THREAD

**Issue by Arny4** [qwertyquerty/pypresence#64]
I starting my app.
Terminal typing me this error:
`Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from pypresence import Presence
  File "C:\Users\Dom\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pypresence\__init__.py", line 7, in <module>
    from .activity import Activity
  File "C:\Users\Dom\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pypresence\activity.py", line 5, in <module>
    from .presence import Presence
  File "C:\Users\Dom\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pypresence\presence.py", line 5, in <module>
    from .baseclient import BaseClient
  File "C:\Users\Dom\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pypresence\baseclient.py", line 31
    self.ipc_path = f'{tempdir}/{pipe_file}'
                                           `
And this error in all apps.
I using python 3.5.4

**Comment by LewdNeko** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAAAAA WHO THE FUCK PUT A FUCKING F STRING IN

**Comment by LewdNeko** [comment]
Re-install the lib with `pip install https://github.com/qwertyquerty/pypresence/archive/master.zip`. Effort to update pypi rn

**Comment by Arny4** [comment]
Thank you very much! :+1:
