### ISSUE TITLE
When running PyPresence

### ISSUE THREAD

**Issue by lilyoungbug** [qwertyquerty/pypresence#69]
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x03904FA8>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\lib\asyncio\proactor_events.py", line 93, in __del__
    warnings.warn(f"unclosed transport {self!r}", ResourceWarning,
  File "C:\Program Files (x86)\Python37-32\lib\asyncio\proactor_events.py", line 57, in __repr__
    info.append(f'fd={self._sock.fileno()}')
  File "C:\Program Files (x86)\Python37-32\lib\asyncio\windows_utils.py", line 102, in fileno
    raise ValueError("I/O operation on closed pipe")
ValueError: I/O operation on closed pipe

**Comment by LewdNeko** [comment]
???
