### ISSUE TITLE
Random error popping up on my friends pc

### ISSUE THREAD

**Issue by TAG-Epic** [qwertyquerty/pypresence#72]
We have the same code and everything, but he gets an error when running it that i dont. 

Traceback
```py
C:\Users\robin\Desktop\devio>python main.py
Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...5781250000"}'>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF...5781250000"}'>)>
Traceback (most recent call last):
  File "C:\Users\robin\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\robin\AppData\Local\Programs\Python\Python37\lib\asyncio\proactor_events.py", line 293, in _loop_reading
    self._data_received(data)
  File "C:\Users\robin\AppData\Local\Programs\Python\Python37\lib\asyncio\proactor_events.py", line 244, in _data_received
    self._protocol.data_received(data)
  File "C:\Users\robin\AppData\Local\Programs\Python\Python37\lib\asyncio\streams.py", line 257, in data_received
    self._stream_reader.feed_data(data)
  File "C:\Users\robin\AppData\Local\Programs\Python\Python37\lib\site-packages\pypresence\client.py", line 56, in on_event
    raise DiscordError(payload["data"]["code"], payload["data"]["message"])
pypresence.exceptions.DiscordError: Error Code: 5000 Message: OAuth2 Error: invalid_scope: The requested scope is invalid, unknown, or malformed.
Traceback (most recent call last):
File "main.py", line 6, in <module>
    sharing.connect()
  File "C:\Users\robin\Desktop\devio\sharing.py", line 17, in connect
    client.authorize(ID, ["rpc"])
  File "C:\Users\robin\AppData\Local\Programs\Python\Python37\lib\site-packages\pypresence\client.py", line 61, in authorize
    return self.loop.run_until_complete(self.read_output())
  File "C:\Users\robin\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "C:\Users\robin\AppData\Local\Programs\Python\Python37\lib\site-packages\pypresence\baseclient.py", line 86, in read_output
    raise ServerError(payload["data"]["message"])
pypresence.exceptions.ServerError: Oauth2 error: invalid_scope: the requested scope is invalid, unknown, or malformed.
```

Part of the code thats causing the issue: 
```py
    client.authorize(ID, ["rpc"])
```

**Comment by BluePhoenixGame** [comment]
Yes, we tested after putting me on the same team and on the whitelist and it still didn't work.

**Comment by TAG-Epic** [comment]
Seems like discord is dropping support for it. Works using game sdk and can verify it only works when you are the the app owner (whitelist does nothing) @LewdNeko

**Comment by LewdNeko** [comment]
Ugh they're dropping support? Yum.
