### ISSUE TITLE
File not found error?

### ISSUE THREAD

**Issue by iranathan** [qwertyquerty/pypresence#73]
Hello, I downloaded this package from this github (not pypi) and Its giving me this: `FileNotFoundError: [Errno 2] No such file or directory`

[full error](https://pastebin.com/1TEQrDnA)

**Comment by Sigma-One** [comment]
Can confirm, same issue

I think it has something to do with Discord deprecating the old RPC API and introducing some sort of "Game SDK" for god knows why

I may be incorrect though

**Comment by maxicc** [comment]
Can you try using Python 3.6.x? I know some async stuff has changed in Python 3.7, and discord.py is also having issues on the latest version.

**Comment by jusplainmike** [comment]
Same issue on python 3.6. Any ideas?

**Comment by qwertyquerty** [comment]
Discord needs to be open

**Comment by jusplainmike** [comment]
Like the discord API needs to be open?

**Comment by jusplainmike** [comment]
`Traceback (most recent call last):
  File "./rich-presence-loop.py", line 7, in <module>
    RPC.connect()  # Start the handshake loop
  File "/usr/local/lib/python3.6/dist-packages/pypresence/presence.py", line 41, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/dist-packages/pypresence/baseclient.py", line 121, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.6/asyncio/streams.py", line 134, in open_unix_connection
    lambda: protocol, path, **kwds)
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 245, in create_unix_connection
    yield from self.sock_connect(sock, path)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/usr/lib/python3.6/asyncio/selector_events.py", line 444, in _sock_connect
    sock.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
`

**Comment by jusplainmike** [comment]
Nevermind I just realized this won't run for a headless system. Thanks for the reply.

**Comment by qwertyquerty** [comment]
Discord needs to be running on the same machine
