### ISSUE TITLE
client id invalid

### ISSUE THREAD

**Issue by Sterzz** [qwertyquerty/pypresence#76]
Used the same code 4 days ago, now it doesnt work... and no. The client id is correct.

**Comment by GhostofGoes** [comment]
Can you share you're code and the error you're getting?

**Comment by Sterzz** [comment]
Its only the ecample script...

`from pypresence import Presence
import time

client_id = '622558194207555584'  
RPC = Presence(client_id)  
RPC.connect()

print(RPC.update(state="Lookie Lookie", details="A test of qwertyquerty's Python Discord RPC wrapper, pypresence!"))  # Set the presence

while True:  
    time.sleep(15) 
`
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\site-packages\pypresence\baseclient.py", line 80, in read_output
    data = await self.sock_reader.read(1024)
  File "C:\Program Files\Python36\lib\asyncio\streams.py", line 615, in read
    raise self._exception
  File "C:\Program Files\Python36\lib\asyncio\proactor_events.py", line 291, in _loop_writing
    self._write_fut = self._loop._proactor.send(self._sock, data)
  File "C:\Program Files\Python36\lib\asyncio\windows_events.py", line 457, in send
    ov.WriteFile(conn.fileno(), buf)
BrokenPipeError: [WinError 232] Die Pipe wird gerade geschlossen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nnell\Documents\Browser Discord RPC\test.py", line 8, in <module>
    print(RPC.update(state="Lookie Lookie", details="A test of qwertyquerty's Python Discord RPC wrapper, pypresence!"))  # Set the presence
  File "C:\Program Files\Python36\lib\site-packages\pypresence\presence.py", line 32, in update
    return self.loop.run_until_complete(self.read_output())
  File "C:\Program Files\Python36\lib\asyncio\base_events.py", line 484, in run_until_complete
    return future.result()
  File "C:\Program Files\Python36\lib\site-packages\pypresence\baseclient.py", line 82, in read_output
    raise InvalidID
pypresence.exceptions.InvalidID: Client ID is Invalid

**Comment by GhostofGoes** [comment]
You need to replace the client ID with one you generate via Discord's developer dashboard.

**Comment by denizsincar29** [comment]
guys, how does the client id work? I installed a vscode extension (discord presence), and it didn't prompt me for client id. it detected the client automatically without the id.
