### ISSUE TITLE
Bug: Brokenpipeerror when closing discord

### ISSUE THREAD

**Issue by DohrliOfDeath** [qwertyquerty/pypresence#80]
Hello, if I start discord, start my program that uses pypresence, close discord and reopen it, try to change my rich presence, it crashes with this error message [I tried to make a try: except: around it, it seems to be ignored]:
```Exception in thread Thread-47:
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/pypresence/baseclient.py", line 99, in read_output
    data = await self.sock_reader.read(1024)
  File "/usr/lib/python3.8/asyncio/streams.py", line 665, in read
    raise self._exception
  File "/usr/lib/python3.8/asyncio/selector_events.py", line 908, in write
    n = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/climp3", line 491, in play
    RPC.update(state=out)
  File "/home/user/.local/lib/python3.8/site-packages/pypresence/presence.py", line 32, in update
    return self.loop.run_until_complete(self.read_output())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/user/.local/lib/python3.8/site-packages/pypresence/baseclient.py", line 101, in read_output
    raise InvalidID
pypresence.exceptions.InvalidID: Client ID is Invalid
```
```
$ pip3 show pypresence
Name: pypresence
Version: 4.0.0
Summary: Discord RPC client written in Python
Home-page: https://github.com/qwertyquerty/pypresence
Author: qwertyquerty
Author-email: None
License: MIT
Location: /home/user/.local/lib/python3.8/site-packages
Requires: 
Required-by:
```

**Comment by rullinoiz** [comment]
maybe make your program check periodically if discord is open and if it isn’t maybe restart the program?

**Comment by DohrliOfDeath** [comment]
Oh yes you're right that works. I think I need to get into the habit to solve the problem that is causing the error instead of just resolving the error. Although I still think pypresence should have something to just ignore the error..
