### ISSUE TITLE
Error while running code.

### ISSUE THREAD

**Issue by 9u3** [qwertyquerty/pypresence#87]
I tried to use it and i got this error:
```
Traceback (most recent call last):
  File "C:\Users\azerb\Desktop\pypresence-master\examples\rich-presence.py", line 8, in <module>
    RPC.update(state="Developing", details="In VSCode!")
  File "C:\Users\azerb\Desktop\pypresence-master\examples\pypresence\presence.py", line 32, in update
    return self.loop.run_until_complete(self.read_output())
  File "C:\Users\azerb\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "C:\Users\azerb\Desktop\pypresence-master\examples\pypresence\baseclient.py", line 105, in read_output
    status_code, length = struct.unpack('<II', data[:8])
struct.error: unpack requires a buffer of 8 bytes
```

what do i do?

**Comment by CoopJax** [comment]
This is more of a question that I would ask on the discord: https://discord.gg/JF3kg77

**Comment by Hunter2807** [comment]
@9u3  pls close this issue if you are done, else join the discord server for better and faster support --> https://discord.gg/FSQmzwj3
