### ISSUE TITLE
self.sock_writer has no attribute 'write

### ISSUE THREAD

**Issue by spookybear0** [qwertyquerty/pypresence#90]
`Traceback (most recent call last):
  File "d:/code/python/projects/PyGDRPC/PyGDRPC/main.py", line 69, in main
    await rpc.update(pid=pid, state=str(f"{name} by {creator} (Attempt {attempt})"),
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pypresence\presence.py", line 65, in update
    self.send_data(1, payload)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\pypresence\baseclient.py", line 112, in send_data
    self.sock_writer.write(
AttributeError: 'NoneType' object has no attribute 'write`

I am using AioPresence, and getting this error for no reason whenever I start my program. 

Code: https://pastebin.com/UhYnCRgJ

**Comment by qwertyquerty** [comment]
more verbose in new release
