### ISSUE TITLE
it dont run

### ISSUE THREAD

**Issue by takipsizad** [qwertyquerty/pypresence#97]
Traceback (most recent call last):
  File "C:\Users\pc\python\lib\site-packages\pypresence\baseclient.py", line 127, in handshake
    self.sock_writer, _ = await self.loop.create_pipe_connection(lambda: reader_protocol, self.ipc_path)
  File "C:\Users\pc\python\lib\asyncio\windows_events.py", line 333, in create_pipe_connection
    pipe = await f
  File "C:\Users\pc\python\lib\asyncio\windows_events.py", line 652, in connect_pipe
    handle = _overlapped.ConnectPipe(address)
FileNotFoundError: [WinError 2] Sistem belirtilen dosyayı bulamıyor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\pc\projeler\terminal\terminal.py", line 26, in <module>
    RPC.connect()
  File "C:\Users\pc\python\lib\site-packages\pypresence\presence.py", line 41, in connect
    self.loop.run_until_complete(self.handshake())
  File "C:\Users\pc\python\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\pc\python\lib\site-packages\pypresence\baseclient.py", line 129, in handshake
    raise InvalidPipe
pypresence.exceptions.InvalidPipe: Pipe Not Found - Is Discord Running?

**Comment by takipsizad** [comment]
i have discord running btw

**Comment by Hunter2807** [comment]
Please convert all the error to English please. In between, it's in a different language. Use only English please

**Comment by takipsizad** [comment]
Sistem belirtilen dosyayı bulamıyor 
system cant find the file

**Comment by WindowsVistaisCool** [comment]
you must run it on a machine with the desktop version of discord installed (i think)
I tried running it within WSL, but it didn't work, so I had to go back to CMD

**Comment by takipsizad** [comment]
oh i used powershell for things
